trigger:
- main

# ✅ 
variables:
  acrServiceConnection: 'sc-acr'                     # Name ACR
  acrLoginServer: 'mydevopsacr14640.azurecr.io'      # ACR 
  imageRepository: 'mywebsite'                       #  Docker-image
  tag: '$(Build.BuildId)'                            # tag

stages:
# ====================== CI stage ======================
- stage: Build
  displayName: Build and Push Image to ACR
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: $(acrServiceConnection)

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: buildAndPush
        repository: $(acrLoginServer)/$(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)

# ====================== CD stage ======================
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Container to Web App
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Web App'
            inputs:
              azureSubscription: 'sc-azure'
              appName: 'myweb123'
              imageName: 'mydevopsacr14640.azurecr.io/mywebsite:latest'
