trigger:
- main

stages:
# ====================== CI stage ======================
- stage: Build
  displayName: Build and Push Image to ACR
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      acrServiceConnection: 'sc-acr'
      acrLoginServer: 'mydevopsacr14640.azurecr.io'
      imageRepository: 'mywebsite'
      tag: '$(Build.BuildId)'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: $(acrServiceConnection)

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: buildAndPush
        repository: $(acrLoginServer)/$(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)

# ====================== CD stage ======================
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Container to Web App
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Web App'
            inputs:
              azureSubscription: 'sc-azure'        # <-- Service connection for ARM (Azure)
              appName: 'myweb123'                  # <-- Имя твоего Web App
              imageName: 'mydevopsacr14640.azurecr.io/mywebsite:latest'
