trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'sc-acr'                           # Имя Service Connection
  acrLoginServer: 'mydevopsacr14640.azurecr.io'            # Твой ACR логин-сервер
  imageRepository: 'mywebsite'                             # Название контейнера
  tag: '$(Build.BuildId)'                                  # Уникальный тег каждого билда

steps:
- checkout: self

# Login в Azure Container Registry
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: $(acrServiceConnection)

# Build + Push Docker image
- task: Docker@2
  displayName: 'Build and Push Image to ACR'
  inputs:
    command: buildAndPush
    repository: $(acrLoginServer)/$(imageRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      latest
      $(tag)
